### ISSUE TITLE
Release v2.6.2

### ISSUE THREAD

**Issue by parkr** [octopress/hooks#15]
Hey @imathis! I merged #14 which fixes #13 and I would love to see that change pushed out. Looking at https://rubygems.org/gems/octopress-hooks, it seems you are the only one with push permissions for RubyGems 😁 Would you mind packaging up master as v2.6.2?

Thank you! ❤️ 

Also fixes https://github.com/octopress/paginate/issues/19

**Comment by budparr** [comment]
Any reason why this couldn't be pulled directly into the jekyll ecosystem, given the death of the old jekyll-paginate?

**Comment by parkr** [comment]
The hooks? They kind of are, in the form of Jekyll::Hook.

This release just puts out a momentary fire. Over time, I would like to
help migrate the Octopress suite of plugins to use Jekyll hooks and
deprecate this gem.

**Comment by budparr** [comment]
Yeah, I meant `octopress-paginate`, not hooks, but this:

> Over time, I would like to help migrate the Octopress suite of plugins to use Jekyll hooks and deprecate this gem.

answers my question. I just thought, naïvely, perhaps that it was merely a matter of changing the org/name.

**Comment by XhmikosR** [comment]
@parkr: this release should be made so that octopress-paginate works again.

**Comment by parkr** [comment]
Done. https://rubygems.org/gems/octopress-hooks/versions/2.6.2

**Comment by XhmikosR** [comment]
Thanks! Now octopress-paginate works again :)

**Comment by JetStarBlues** [comment]
@parkr  Do these changes have anything to do with `octopress-date-format` failing to work when upgraded to its Jekyll 3 compatible version?  (See [open issue][1].)

Specifically this statement:
> The hooks? They kind of are, in the form of Jekyll::Hook. This release just puts out a momentary fire. Over time, I would like to help migrate the Octopress suite of plugins to use Jekyll hooks and deprecate this gem.

It seems the file [octopress_filters.rb][2] uses `Octopress::Hooks`. Maybe there is a conflict?

[1]: https://github.com/octopress/date-format/issues/6
[2]: https://github.com/imathis/octopress/blob/master/plugins/octopress_filters.rb
