### ISSUE TITLE
Collection rendering problem in v2.4.0

### ISSUE THREAD

**Issue by mdotasia** [octopress/hooks#9]
In my ink theme I have a collection of Markdown files that is not rendered by default. I access collection items from within a template and render them using `collection_item.output` (see http://jekyllrb.com/docs/collections/, see last section). This should render the collection item markdown file including applying a layout.

I noticed that since hooks v2.4.0 the rendering of the collection item breaks. When I use `collection_item.output` I get the content of the collection item markdown (everything below the second `---`). This is the same result as if I would use `collection_item.content`.

But `collection_item.output` should be rendered while `collection_item.content` should not be rendered.

**Comment by mdotasia** [comment]
Forgot to mention that everything works fine in v2.3.2.

**Comment by imathis** [comment]
Thanks for filing this issue. Do you have a link to your source so I can get a clearer idea of what you're working with? Or could you help describe steps to reproduce what you're seeing?

**Comment by imathis** [comment]
Actually looking at the changes in 2.4.0, I think I know what to do. I've just released 2.4.1. If you would update and let me know if that fixes it for you, I'd appreciate it.

**Comment by mdotasia** [comment]
I confirm that v2.4.1 fixed it. Perfect!

**Comment by imathis** [comment]
Hot diggity. Thanks for helping me find a bug so fast. I appreciate your willingness to use this stuff hot out of the oven. :)

**Comment by mdotasia** [comment]
I typed `bundle update` to fast and then I had no other choice but helping :) I'm using your Octopress family of plugins for this: https://github.com/UNStats/UNStats-theme. This will be the basis for two smaller websites and if successful I hope we will go Jekyll only.

**Comment by imathis** [comment]
That's awesome. I hope it goes well for you. Do you think you'll have any use for the [octopress-multilingual](https://github.com/octopress/multilingual) plugin?

**Comment by mdotasia** [comment]
It's on my radar. But it may still take a while until I have a chance to play with it.
